builder/bootstrap
pkg.list

During `apt update` I got the error
W: http://repo.gardenlinux.io/gardenlinux/dists/today/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/keyring.gpg are ignored as the file has an unsupported filetype.
The reason was, that the `keyring.gpg` was copied to `/etc/apt/trusted.gpg.d/` in a wrong format.
Please also check the current gardenlinux builds for this error.

exporting keyring in asc format for apt/trusted.gpg.d directory

---

pkg.list

We need this in the builder to be able to build GL iso images.

Add xorriso to pkg.list

---

builder/parse_features

Fixes unbound variable errors when omitting the `arch` or `version` cmd-line parameter and adds a `cname_base` command that only prints out the cname without version and arch.
**Release note**:
```feature user
Fixes unbound variable errors when omitting the `arch` or `version` cmd-line parameter and adds a `cname_base` command that only prints out the cname without version and arch.
```

fix unbound variables and add cname_base cmd

---

builder/image.d/makepart

Allow /efi as boot partition as well

Allow /efi as boot partition as well

---

.github/workflows/build.yml
Dockerfile

Dependabot expects the link to the source repo as described here: 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker

Configure docker metadata for dependabot

---

.github/dependabot.yml
.github/workflows/differential-shellcheck.yml

* add differential shellcheck gh action
* add dependabot config for keeping shellchek up to date

Add differential shellcheck action

---

build

This change allows to track the used Builder tag in a Dockerfile. This is useful for using Dependabot to keep the builder version up to date.
Users of the Builder who wish to use Dependabot will need to create a `builder.dockerfile` next to their `build` script with the following contents:
```
FROM ghcr.io/gardenlinux/builder:SHA
```
Where SHA will be updated by dependabot if configured correctly.
also users will need to set the `container_image` value in `build` to `localhost/builder`

Build from 'builder.dockerfile' if exists

---

.github/workflows/build.yml
.github/workflows/bump.py

This PR implements a release workflow for a introducing semantic versions to the builder.
Minor version updates are expected to be compatible between the `build` script and the OCI image.
Major version upgrades may introduce breaking changes between the `build` script and the OCI image.
This change will improve how the builder can be kept up to date with dependabot.

Release Workflow

---

builder/parse_features

If a feature references a non existing featute, then the builder should exit with an error message telling the user that this feature does not exist.
**Which issue(s) this PR fixes**:
Fixes #22

fix: add check if referenced feature does exist

---

build

This change is needed to allow keeping the builder updated via dependabot.

Build from 'builder.dockerfile' if that exists

---

.github/workflows/README.md
.github/workflows/build.yml
.github/workflows/release.yml

Cleanly separate the build (push on main) and release (new version number) workflow. The build workflow should work like it did before the release workflow was introduced. The release workflow is not supposed to build a new image, but instead to take the latest built image and apply the tag of the new version to it.

Split build and release workflow

---

Dockerfile

openssl in testing breaks aws kms pkcs11 module support

fix: temporarily use debian stable

---

.github/workflows/build.yml
.github/workflows/release.yml
build
build.config
builder/Makefile
builder/bootstrap
builder/configure
builder/configure_nativetools
builder/image
builder/image.d/makepart
builder/image.d/makesecureboot

In some cases, the current hard-coded size limit for tempfs makes it impossible to build images with the builder. This change introduces a new config interface via a 'build.config' file which builder users might use to override selected variables.
Note that this introduces a *breaking change* in the sense that the `build` script needs to define the `tempfs_size` variable like in this example
```
tempfs_size=2G
if [[ -f "$PWD"/build.config ]]; then
. "$PWD"/build.config
fi
make_opts+=("TEMPFS_SIZE=$tempfs_size")
```
If this is not done, an error like `Makefile:25: *** 'TEMPFS_SIZE undefined'.  Stop.` will occur.
Fixes #54
Needed for https://github.com/gardenlinux/dev-image/pull/3

Make tempfs size configurable via new 'build.config' file

---

builder/parse_features

This adds a new 'graph' command to `parse_features`.
This command prints the text representation of a [mermaid js](https://mermaid.js.org/syntax/flowchart.html?id=flowcharts-basic-syntax) flowchart/graph.
This output can be embedded into [GitHub flavoured markdown](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams) files.
I used the following command to run the script:
```
builder/builder/parse_features  --feature-dir gardenlinux/features/ --arch `dpkg --print-architecture` --version today --cname kvm graph
```
where the `cname` argument can be any feature.

Print graph of feature dependencies

---

build

In order to use a local dev version of the builder, the documentation tells the user to do the following:
```
cd gardenlinux
ln -f -s ../builder/build build
```
Furthermore, the docs suggest that the builder would re-build the docker file if necessary. 
However, this is currently not working because the link detects the gardenlinux/builder.dockerfile and uses it instead of the local builder.

fix: rebuild local docker file in local development case

---

builder/image.d/make_repart_disk
builder/image.d/makepart
builder/image.d/makesecureboot
pkg.list

This PR changes the current encryption behaviour in favour of binding to signatures of PCR 11 values with signed public key based policies. Binding to PCR 7 is kept static, as the Secure Boot state should not change during e.g. a kernel upgrade.
Following steps are being performed during the build process if a partition with the feature flag `tpm2` is defined in the `fstab.mod` file:
1. PCR 11 values get pre-calculated during the build process using `ukfiy`(could be changed in the future to `systemd-measure`)
2. Generates a valid PCR signature JSON for the given build based on the values calculated in Step 1
3. Combines `.pcrsig` and `.pcrpkey` sections into the final bootable Unified Kernel Image
4. _Optional:_ This UKI file can also be signed if Secure Boot is enabled
These steps are …

Pre-calculate and sign `PCR 11` values on build

---

Dockerfile
setup_namespace

use https://github.com/gardenlinux/seccomp_fake_xattr to enable selinux bulids on selinux hosts

feat: seccomp_fake_xattr

---

build
setup_namespace

having it in container entrypoint breaks tests, as test leaves orphaned processes running => causing test to never terminate 
(TODO: fix tests, to not leave processes running once completed)

move fake_xattr to build time only

---

.github/workflows/release.yml

The image of version 0.3 does not properly contain the multi-arch image as expected. It looks like 'manifest push' is the command we should use rather than 'image push'.
Note: As of today, github actions has podman v 3.x
The cli has changed in those versions, see:
- docs for v3 https://docs.podman.io/en/v3.0/markdown/podman-manifest-push.1.html
- docs for current https://docs.podman.io/en/stable/markdown/podman-manifest-push.1.html

Fix tags for release image by using manifest push

---

builder/bootstrap
pkg.list

currently building debian testing based images with debootstrap is broken due to the `t64` transition and debootstrap not handling `Provides: ` fields in the package index.
=> Let's switch to mmdebstrap which uses apt under the hood, thus handling `Provides: ` fields correctly

use mmdebstrap instead of debootstrap

---

build
builder/image.d/make_reproducible_ext4

=> allow building with 4G mem cap
gardenlinux test run: [✅  9794518731](https://github.com/gardenlinux/gardenlinux/actions/runs/9794518731)

feat: make ext4 building require less memory

---

.github/workflows/build.yml

* main branch has branch protection, so only maintainers must be allowed to trigger publish process (which is enforced already)
* PR pipelines need to check if build works, so we must skip publishing in order to get green pipelines

only publish to ghcr.io if pipeline runs on main branch

---

builder/image.manifest

new podman machine now uses rosetta to emulate x86 on arm macos, rosetta, however, always requires /proc/ to be mounted in any chroot

fix: make cross-arch build work with rosetta on mac

---

builder/image.d/makepart

The UEFI standard allows all human readable characters, and systemd-sysupdate encodes there a version string.
So relax the constraint to 'printing characters, excluding space', as a compromise.
**Which issue(s) this PR fixes**:
Fixes #98
**Special notes for your reviewer**:
**Release note**:
```bugfix| user
Relax constraints on labels for partitions.
```

Relax constraints for partition label

---

builder/bootstrap

If the config repo is cloned with umask such that the keyring.gpg file is not world readable, then trying to read it with the _apt user fails.
Therefore, let's disable apt sandboxing in mmdebstrap as everything is containerized anyways.
fixes #102

fix: run mmdebstrap without apt sandbox user

---

Dockerfile
pkg.list

Using `datefudge` to ensure reproducible secureboot signatures with `sbsign` works well for local keys, but when using remote signing providers like aws kms this breaks due to SSL sessions also being established with faked time info.
This patched version of sbsigntool introduces an optional env var `SBSIGN_FAKETIME` to overwrite the signature timestamp without effecting the entire process.

feat: use patched sbsigntool

---

build

After using the apparmor builder profile from `/etc/apparmor.d/containers/builder` for a build using docker as the container engine, the build didn't work anymore after rebooting the machine.
It failed because the builder profile was not enabled anymore, as apparmor only automatically enables profiles directly located at `/etc/apparmor.d/`.
This PR fixes this issue by changing the builder profile path from `/etc/apparmor.d/containers/builder` to `/etc/apparmor.d/builder`

fix: apparmor build profile is disabled after reboot

---

Dockerfile

- When building the container_image for testing, the aws sdk was built to compile aws_kms_pkcs11.so
- This was very slow, therefore the library is now downloaded directly from [gardenlinux/aws-kms-pkcs11](https://github.com/gardenlinux/aws-kms-pkcs11)

download aws_kms_pkcs11.so from gardenlinux/aws-kms-pkcs11

---

build
builder/make_log

To support short log console messages if executed in CI environments `$CI` is considered nd if set to `true` removes date&time information.
**Which issue(s) this PR fixes**:
Fixes #36

This commit supports `$LOG_WITH_TIMESTAMP` to generate shorter log output
